// Automatically generated product data

export const products = [
  {
    "id": 1,
    "name": "Napa 250mg",
    "category": "Medicines",
    "description": "Relief for common ailments and symptoms.",
    "details": "This is a high-quality medicines manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳36.00 / strip",
    "manufacturer": "Beximco Pharmaceuticals Ltd.",
    "inStock": true,
    "packSize": "10 tablets per strip"
  },
  {
    "id": 2,
    "name": "Napa 500mg",
    "category": "Medicines",
    "description": "Relief for common ailments and symptoms.",
    "details": "This is a high-quality medicines manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳22.00 / strip",
    "manufacturer": "Aristopharma Ltd.",
    "inStock": true,
    "packSize": "10 tablets per strip"
  },
  {
    "id": 3,
    "name": "Napa 1000mg",
    "category": "Medicines",
    "description": "Relief for common ailments and symptoms.",
    "details": "This is a high-quality medicines manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳51.00 / strip",
    "manufacturer": "Beximco Pharmaceuticals Ltd.",
    "inStock": true,
    "packSize": "10 tablets per strip"
  },
  {
    "id": 4,
    "name": "Seclo 250mg",
    "category": "Medicines",
    "description": "Relief for common ailments and symptoms.",
    "details": "This is a high-quality medicines manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳52.00 / strip",
    "manufacturer": "ACME Laboratories Ltd.",
    "inStock": false,
    "packSize": "10 tablets per strip"
  },
  {
    "id": 5,
    "name": "Seclo 500mg",
    "category": "Medicines",
    "description": "Relief for common ailments and symptoms.",
    "details": "This is a high-quality medicines manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳32.00 / strip",
    "manufacturer": "Opsonin Pharma Limited",
    "inStock": true,
    "packSize": "10 tablets per strip"
  },
  {
    "id": 6,
    "name": "Seclo 1000mg",
    "category": "Medicines",
    "description": "Relief for common ailments and symptoms.",
    "details": "This is a high-quality medicines manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳23.00 / strip",
    "manufacturer": "Opsonin Pharma Limited",
    "inStock": true,
    "packSize": "10 tablets per strip"
  },
  {
    "id": 7,
    "name": "Maxpro 250mg",
    "category": "Medicines",
    "description": "Relief for common ailments and symptoms.",
    "details": "This is a high-quality medicines manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳62.00 / strip",
    "manufacturer": "Square Pharmaceuticals Ltd.",
    "inStock": false,
    "packSize": "10 tablets per strip"
  },
  {
    "id": 8,
    "name": "Maxpro 500mg",
    "category": "Medicines",
    "description": "Relief for common ailments and symptoms.",
    "details": "This is a high-quality medicines manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳56.00 / strip",
    "manufacturer": "Renata Limited",
    "inStock": true,
    "packSize": "10 tablets per strip"
  },
  {
    "id": 9,
    "name": "Maxpro 1000mg",
    "category": "Medicines",
    "description": "Relief for common ailments and symptoms.",
    "details": "This is a high-quality medicines manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳29.00 / strip",
    "manufacturer": "Beximco Pharmaceuticals Ltd.",
    "inStock": true,
    "packSize": "10 tablets per strip"
  },
  {
    "id": 10,
    "name": "Finix 250mg",
    "category": "Medicines",
    "description": "Relief for common ailments and symptoms.",
    "details": "This is a high-quality medicines manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳23.00 / strip",
    "manufacturer": "Renata Limited",
    "inStock": true,
    "packSize": "10 tablets per strip"
  },
  {
    "id": 11,
    "name": "Finix 500mg",
    "category": "Medicines",
    "description": "Relief for common ailments and symptoms.",
    "details": "This is a high-quality medicines manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳33.00 / strip",
    "manufacturer": "Incepta Pharmaceuticals Ltd.",
    "inStock": false,
    "packSize": "10 tablets per strip"
  },
  {
    "id": 12,
    "name": "Finix 1000mg",
    "category": "Medicines",
    "description": "Relief for common ailments and symptoms.",
    "details": "This is a high-quality medicines manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳32.00 / strip",
    "manufacturer": "Opsonin Pharma Limited",
    "inStock": true,
    "packSize": "10 tablets per strip"
  },
  {
    "id": 13,
    "name": "Sergel 250mg",
    "category": "Medicines",
    "description": "Relief for common ailments and symptoms.",
    "details": "This is a high-quality medicines manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳55.00 / strip",
    "manufacturer": "Beximco Pharmaceuticals Ltd.",
    "inStock": true,
    "packSize": "10 tablets per strip"
  },
  {
    "id": 14,
    "name": "Sergel 500mg",
    "category": "Medicines",
    "description": "Relief for common ailments and symptoms.",
    "details": "This is a high-quality medicines manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳20.00 / strip",
    "manufacturer": "Incepta Pharmaceuticals Ltd.",
    "inStock": true,
    "packSize": "10 tablets per strip"
  },
  {
    "id": 15,
    "name": "Sergel 1000mg",
    "category": "Medicines",
    "description": "Relief for common ailments and symptoms.",
    "details": "This is a high-quality medicines manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳54.00 / strip",
    "manufacturer": "ACME Laboratories Ltd.",
    "inStock": true,
    "packSize": "10 tablets per strip"
  },
  {
    "id": 16,
    "name": "Losectil 250mg",
    "category": "Medicines",
    "description": "Relief for common ailments and symptoms.",
    "details": "This is a high-quality medicines manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳46.00 / strip",
    "manufacturer": "Square Pharmaceuticals Ltd.",
    "inStock": true,
    "packSize": "10 tablets per strip"
  },
  {
    "id": 17,
    "name": "Losectil 500mg",
    "category": "Medicines",
    "description": "Relief for common ailments and symptoms.",
    "details": "This is a high-quality medicines manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳30.00 / strip",
    "manufacturer": "Renata Limited",
    "inStock": true,
    "packSize": "10 tablets per strip"
  },
  {
    "id": 18,
    "name": "Losectil 1000mg",
    "category": "Medicines",
    "description": "Relief for common ailments and symptoms.",
    "details": "This is a high-quality medicines manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳43.00 / strip",
    "manufacturer": "Renata Limited",
    "inStock": false,
    "packSize": "10 tablets per strip"
  },
  {
    "id": 19,
    "name": "Bextram 250mg",
    "category": "Medicines",
    "description": "Relief for common ailments and symptoms.",
    "details": "This is a high-quality medicines manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳40.00 / strip",
    "manufacturer": "Square Pharmaceuticals Ltd.",
    "inStock": true,
    "packSize": "10 tablets per strip"
  },
  {
    "id": 20,
    "name": "Bextram 500mg",
    "category": "Medicines",
    "description": "Relief for common ailments and symptoms.",
    "details": "This is a high-quality medicines manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳36.00 / strip",
    "manufacturer": "Eskayef Pharmaceuticals Ltd.",
    "inStock": true,
    "packSize": "10 tablets per strip"
  },
  {
    "id": 21,
    "name": "Bextram 1000mg",
    "category": "Medicines",
    "description": "Relief for common ailments and symptoms.",
    "details": "This is a high-quality medicines manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳61.00 / strip",
    "manufacturer": "ACME Laboratories Ltd.",
    "inStock": true,
    "packSize": "10 tablets per strip"
  },
  {
    "id": 22,
    "name": "Calbo 250mg",
    "category": "Medicines",
    "description": "Relief for common ailments and symptoms.",
    "details": "This is a high-quality medicines manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳28.00 / strip",
    "manufacturer": "Incepta Pharmaceuticals Ltd.",
    "inStock": true,
    "packSize": "10 tablets per strip"
  },
  {
    "id": 23,
    "name": "Calbo 500mg",
    "category": "Medicines",
    "description": "Relief for common ailments and symptoms.",
    "details": "This is a high-quality medicines manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳50.00 / strip",
    "manufacturer": "Incepta Pharmaceuticals Ltd.",
    "inStock": true,
    "packSize": "10 tablets per strip"
  },
  {
    "id": 24,
    "name": "Calbo 1000mg",
    "category": "Medicines",
    "description": "Relief for common ailments and symptoms.",
    "details": "This is a high-quality medicines manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳56.00 / strip",
    "manufacturer": "Beximco Pharmaceuticals Ltd.",
    "inStock": true,
    "packSize": "10 tablets per strip"
  },
  {
    "id": 25,
    "name": "Odmon 250mg",
    "category": "Medicines",
    "description": "Relief for common ailments and symptoms.",
    "details": "This is a high-quality medicines manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳27.00 / strip",
    "manufacturer": "Renata Limited",
    "inStock": true,
    "packSize": "10 tablets per strip"
  },
  {
    "id": 26,
    "name": "Odmon 500mg",
    "category": "Medicines",
    "description": "Relief for common ailments and symptoms.",
    "details": "This is a high-quality medicines manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳35.00 / strip",
    "manufacturer": "Incepta Pharmaceuticals Ltd.",
    "inStock": true,
    "packSize": "10 tablets per strip"
  },
  {
    "id": 27,
    "name": "Odmon 1000mg",
    "category": "Medicines",
    "description": "Relief for common ailments and symptoms.",
    "details": "This is a high-quality medicines manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳64.00 / strip",
    "manufacturer": "Beximco Pharmaceuticals Ltd.",
    "inStock": true,
    "packSize": "10 tablets per strip"
  },
  {
    "id": 28,
    "name": "Esonix 250mg",
    "category": "Medicines",
    "description": "Relief for common ailments and symptoms.",
    "details": "This is a high-quality medicines manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳28.00 / strip",
    "manufacturer": "Opsonin Pharma Limited",
    "inStock": true,
    "packSize": "10 tablets per strip"
  },
  {
    "id": 29,
    "name": "Esonix 500mg",
    "category": "Medicines",
    "description": "Relief for common ailments and symptoms.",
    "details": "This is a high-quality medicines manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳61.00 / strip",
    "manufacturer": "Opsonin Pharma Limited",
    "inStock": true,
    "packSize": "10 tablets per strip"
  },
  {
    "id": 30,
    "name": "Esonix 1000mg",
    "category": "Medicines",
    "description": "Relief for common ailments and symptoms.",
    "details": "This is a high-quality medicines manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳59.00 / strip",
    "manufacturer": "Opsonin Pharma Limited",
    "inStock": true,
    "packSize": "10 tablets per strip"
  },
  {
    "id": 31,
    "name": "Fexo 250mg",
    "category": "Medicines",
    "description": "Relief for common ailments and symptoms.",
    "details": "This is a high-quality medicines manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳50.00 / strip",
    "manufacturer": "Beximco Pharmaceuticals Ltd.",
    "inStock": false,
    "packSize": "10 tablets per strip"
  },
  {
    "id": 32,
    "name": "Fexo 500mg",
    "category": "Medicines",
    "description": "Relief for common ailments and symptoms.",
    "details": "This is a high-quality medicines manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳41.00 / strip",
    "manufacturer": "Incepta Pharmaceuticals Ltd.",
    "inStock": true,
    "packSize": "10 tablets per strip"
  },
  {
    "id": 33,
    "name": "Fexo 1000mg",
    "category": "Medicines",
    "description": "Relief for common ailments and symptoms.",
    "details": "This is a high-quality medicines manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳48.00 / strip",
    "manufacturer": "Aristopharma Ltd.",
    "inStock": true,
    "packSize": "10 tablets per strip"
  },
  {
    "id": 34,
    "name": "Alatrol 250mg",
    "category": "Medicines",
    "description": "Relief for common ailments and symptoms.",
    "details": "This is a high-quality medicines manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳26.00 / strip",
    "manufacturer": "Renata Limited",
    "inStock": true,
    "packSize": "10 tablets per strip"
  },
  {
    "id": 35,
    "name": "Alatrol 500mg",
    "category": "Medicines",
    "description": "Relief for common ailments and symptoms.",
    "details": "This is a high-quality medicines manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳55.00 / strip",
    "manufacturer": "Aristopharma Ltd.",
    "inStock": true,
    "packSize": "10 tablets per strip"
  },
  {
    "id": 36,
    "name": "Alatrol 1000mg",
    "category": "Medicines",
    "description": "Relief for common ailments and symptoms.",
    "details": "This is a high-quality medicines manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳34.00 / strip",
    "manufacturer": "Opsonin Pharma Limited",
    "inStock": true,
    "packSize": "10 tablets per strip"
  },
  {
    "id": 37,
    "name": "Monas 250mg",
    "category": "Medicines",
    "description": "Relief for common ailments and symptoms.",
    "details": "This is a high-quality medicines manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳61.00 / strip",
    "manufacturer": "Square Pharmaceuticals Ltd.",
    "inStock": true,
    "packSize": "10 tablets per strip"
  },
  {
    "id": 38,
    "name": "Monas 500mg",
    "category": "Medicines",
    "description": "Relief for common ailments and symptoms.",
    "details": "This is a high-quality medicines manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳60.00 / strip",
    "manufacturer": "ACME Laboratories Ltd.",
    "inStock": true,
    "packSize": "10 tablets per strip"
  },
  {
    "id": 39,
    "name": "Monas 1000mg",
    "category": "Medicines",
    "description": "Relief for common ailments and symptoms.",
    "details": "This is a high-quality medicines manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳27.00 / strip",
    "manufacturer": "Opsonin Pharma Limited",
    "inStock": true,
    "packSize": "10 tablets per strip"
  },
  {
    "id": 40,
    "name": "Comet 250mg",
    "category": "Medicines",
    "description": "Relief for common ailments and symptoms.",
    "details": "This is a high-quality medicines manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳36.00 / strip",
    "manufacturer": "Beximco Pharmaceuticals Ltd.",
    "inStock": true,
    "packSize": "10 tablets per strip"
  },
  {
    "id": 41,
    "name": "Comet 500mg",
    "category": "Medicines",
    "description": "Relief for common ailments and symptoms.",
    "details": "This is a high-quality medicines manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳65.00 / strip",
    "manufacturer": "Opsonin Pharma Limited",
    "inStock": true,
    "packSize": "10 tablets per strip"
  },
  {
    "id": 42,
    "name": "Comet 1000mg",
    "category": "Medicines",
    "description": "Relief for common ailments and symptoms.",
    "details": "This is a high-quality medicines manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳32.00 / strip",
    "manufacturer": "Eskayef Pharmaceuticals Ltd.",
    "inStock": true,
    "packSize": "10 tablets per strip"
  },
  {
    "id": 43,
    "name": "Normens 250mg",
    "category": "Medicines",
    "description": "Relief for common ailments and symptoms.",
    "details": "This is a high-quality medicines manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳28.00 / strip",
    "manufacturer": "Beximco Pharmaceuticals Ltd.",
    "inStock": true,
    "packSize": "10 tablets per strip"
  },
  {
    "id": 44,
    "name": "Normens 500mg",
    "category": "Medicines",
    "description": "Relief for common ailments and symptoms.",
    "details": "This is a high-quality medicines manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳44.00 / strip",
    "manufacturer": "ACME Laboratories Ltd.",
    "inStock": false,
    "packSize": "10 tablets per strip"
  },
  {
    "id": 45,
    "name": "Normens 1000mg",
    "category": "Medicines",
    "description": "Relief for common ailments and symptoms.",
    "details": "This is a high-quality medicines manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳41.00 / strip",
    "manufacturer": "Aristopharma Ltd.",
    "inStock": true,
    "packSize": "10 tablets per strip"
  },
  {
    "id": 46,
    "name": "Bizoran 250mg",
    "category": "Medicines",
    "description": "Relief for common ailments and symptoms.",
    "details": "This is a high-quality medicines manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳48.00 / strip",
    "manufacturer": "Eskayef Pharmaceuticals Ltd.",
    "inStock": true,
    "packSize": "10 tablets per strip"
  },
  {
    "id": 47,
    "name": "Bizoran 500mg",
    "category": "Medicines",
    "description": "Relief for common ailments and symptoms.",
    "details": "This is a high-quality medicines manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳52.00 / strip",
    "manufacturer": "Opsonin Pharma Limited",
    "inStock": true,
    "packSize": "10 tablets per strip"
  },
  {
    "id": 48,
    "name": "Bizoran 1000mg",
    "category": "Medicines",
    "description": "Relief for common ailments and symptoms.",
    "details": "This is a high-quality medicines manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳51.00 / strip",
    "manufacturer": "ACME Laboratories Ltd.",
    "inStock": true,
    "packSize": "10 tablets per strip"
  },
  {
    "id": 49,
    "name": "Camlosart 250mg",
    "category": "Medicines",
    "description": "Relief for common ailments and symptoms.",
    "details": "This is a high-quality medicines manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳32.00 / strip",
    "manufacturer": "Aristopharma Ltd.",
    "inStock": true,
    "packSize": "10 tablets per strip"
  },
  {
    "id": 50,
    "name": "Camlosart 500mg",
    "category": "Medicines",
    "description": "Relief for common ailments and symptoms.",
    "details": "This is a high-quality medicines manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳69.00 / strip",
    "manufacturer": "Square Pharmaceuticals Ltd.",
    "inStock": true,
    "packSize": "10 tablets per strip"
  },
  {
    "id": 51,
    "name": "Camlosart 1000mg",
    "category": "Medicines",
    "description": "Relief for common ailments and symptoms.",
    "details": "This is a high-quality medicines manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳66.00 / strip",
    "manufacturer": "Aristopharma Ltd.",
    "inStock": true,
    "packSize": "10 tablets per strip"
  },
  {
    "id": 52,
    "name": "Osartil 250mg",
    "category": "Medicines",
    "description": "Relief for common ailments and symptoms.",
    "details": "This is a high-quality medicines manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳42.00 / strip",
    "manufacturer": "Aristopharma Ltd.",
    "inStock": true,
    "packSize": "10 tablets per strip"
  },
  {
    "id": 53,
    "name": "Osartil 500mg",
    "category": "Medicines",
    "description": "Relief for common ailments and symptoms.",
    "details": "This is a high-quality medicines manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳51.00 / strip",
    "manufacturer": "Eskayef Pharmaceuticals Ltd.",
    "inStock": true,
    "packSize": "10 tablets per strip"
  },
  {
    "id": 54,
    "name": "Osartil 1000mg",
    "category": "Medicines",
    "description": "Relief for common ailments and symptoms.",
    "details": "This is a high-quality medicines manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳42.00 / strip",
    "manufacturer": "Square Pharmaceuticals Ltd.",
    "inStock": true,
    "packSize": "10 tablets per strip"
  },
  {
    "id": 55,
    "name": "Angilock 250mg",
    "category": "Medicines",
    "description": "Relief for common ailments and symptoms.",
    "details": "This is a high-quality medicines manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳49.00 / strip",
    "manufacturer": "Renata Limited",
    "inStock": true,
    "packSize": "10 tablets per strip"
  },
  {
    "id": 56,
    "name": "Angilock 500mg",
    "category": "Medicines",
    "description": "Relief for common ailments and symptoms.",
    "details": "This is a high-quality medicines manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳21.00 / strip",
    "manufacturer": "Square Pharmaceuticals Ltd.",
    "inStock": true,
    "packSize": "10 tablets per strip"
  },
  {
    "id": 57,
    "name": "Angilock 1000mg",
    "category": "Medicines",
    "description": "Relief for common ailments and symptoms.",
    "details": "This is a high-quality medicines manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳27.00 / strip",
    "manufacturer": "Renata Limited",
    "inStock": false,
    "packSize": "10 tablets per strip"
  },
  {
    "id": 58,
    "name": "Indever 250mg",
    "category": "Medicines",
    "description": "Relief for common ailments and symptoms.",
    "details": "This is a high-quality medicines manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳59.00 / strip",
    "manufacturer": "Aristopharma Ltd.",
    "inStock": true,
    "packSize": "10 tablets per strip"
  },
  {
    "id": 59,
    "name": "Indever 500mg",
    "category": "Medicines",
    "description": "Relief for common ailments and symptoms.",
    "details": "This is a high-quality medicines manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳50.00 / strip",
    "manufacturer": "Beximco Pharmaceuticals Ltd.",
    "inStock": true,
    "packSize": "10 tablets per strip"
  },
  {
    "id": 60,
    "name": "Indever 1000mg",
    "category": "Medicines",
    "description": "Relief for common ailments and symptoms.",
    "details": "This is a high-quality medicines manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳44.00 / strip",
    "manufacturer": "Eskayef Pharmaceuticals Ltd.",
    "inStock": true,
    "packSize": "10 tablets per strip"
  },
  {
    "id": 61,
    "name": "Cef-3 250mg",
    "category": "Antibiotics",
    "description": "Effective treatment for bacterial infections.",
    "details": "This is a high-quality antibiotics manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳71.00 / strip",
    "manufacturer": "Square Pharmaceuticals Ltd.",
    "inStock": true,
    "packSize": "10 capsules per strip"
  },
  {
    "id": 62,
    "name": "Cef-3 500mg",
    "category": "Antibiotics",
    "description": "Effective treatment for bacterial infections.",
    "details": "This is a high-quality antibiotics manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳58.00 / strip",
    "manufacturer": "Eskayef Pharmaceuticals Ltd.",
    "inStock": true,
    "packSize": "10 capsules per strip"
  },
  {
    "id": 63,
    "name": "Cef-3 1000mg",
    "category": "Antibiotics",
    "description": "Effective treatment for bacterial infections.",
    "details": "This is a high-quality antibiotics manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳89.00 / strip",
    "manufacturer": "Renata Limited",
    "inStock": true,
    "packSize": "10 capsules per strip"
  },
  {
    "id": 64,
    "name": "Moxacil 250mg",
    "category": "Antibiotics",
    "description": "Effective treatment for bacterial infections.",
    "details": "This is a high-quality antibiotics manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳83.00 / strip",
    "manufacturer": "Renata Limited",
    "inStock": true,
    "packSize": "10 capsules per strip"
  },
  {
    "id": 65,
    "name": "Moxacil 500mg",
    "category": "Antibiotics",
    "description": "Effective treatment for bacterial infections.",
    "details": "This is a high-quality antibiotics manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳64.00 / strip",
    "manufacturer": "Incepta Pharmaceuticals Ltd.",
    "inStock": true,
    "packSize": "10 capsules per strip"
  },
  {
    "id": 66,
    "name": "Moxacil 1000mg",
    "category": "Antibiotics",
    "description": "Effective treatment for bacterial infections.",
    "details": "This is a high-quality antibiotics manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳96.00 / strip",
    "manufacturer": "Square Pharmaceuticals Ltd.",
    "inStock": true,
    "packSize": "10 capsules per strip"
  },
  {
    "id": 67,
    "name": "Amoxil 250mg",
    "category": "Antibiotics",
    "description": "Effective treatment for bacterial infections.",
    "details": "This is a high-quality antibiotics manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳91.00 / strip",
    "manufacturer": "Square Pharmaceuticals Ltd.",
    "inStock": false,
    "packSize": "10 capsules per strip"
  },
  {
    "id": 68,
    "name": "Amoxil 500mg",
    "category": "Antibiotics",
    "description": "Effective treatment for bacterial infections.",
    "details": "This is a high-quality antibiotics manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳86.00 / strip",
    "manufacturer": "Square Pharmaceuticals Ltd.",
    "inStock": true,
    "packSize": "10 capsules per strip"
  },
  {
    "id": 69,
    "name": "Amoxil 1000mg",
    "category": "Antibiotics",
    "description": "Effective treatment for bacterial infections.",
    "details": "This is a high-quality antibiotics manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳57.00 / strip",
    "manufacturer": "Incepta Pharmaceuticals Ltd.",
    "inStock": false,
    "packSize": "10 capsules per strip"
  },
  {
    "id": 70,
    "name": "Azithromycin 250mg",
    "category": "Antibiotics",
    "description": "Effective treatment for bacterial infections.",
    "details": "This is a high-quality antibiotics manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳59.00 / strip",
    "manufacturer": "Incepta Pharmaceuticals Ltd.",
    "inStock": true,
    "packSize": "10 capsules per strip"
  },
  {
    "id": 71,
    "name": "Azithromycin 500mg",
    "category": "Antibiotics",
    "description": "Effective treatment for bacterial infections.",
    "details": "This is a high-quality antibiotics manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳70.00 / strip",
    "manufacturer": "Opsonin Pharma Limited",
    "inStock": true,
    "packSize": "10 capsules per strip"
  },
  {
    "id": 72,
    "name": "Azithromycin 1000mg",
    "category": "Antibiotics",
    "description": "Effective treatment for bacterial infections.",
    "details": "This is a high-quality antibiotics manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳67.00 / strip",
    "manufacturer": "Renata Limited",
    "inStock": true,
    "packSize": "10 capsules per strip"
  },
  {
    "id": 73,
    "name": "Zimax 250mg",
    "category": "Antibiotics",
    "description": "Effective treatment for bacterial infections.",
    "details": "This is a high-quality antibiotics manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳62.00 / strip",
    "manufacturer": "Incepta Pharmaceuticals Ltd.",
    "inStock": false,
    "packSize": "10 capsules per strip"
  },
  {
    "id": 74,
    "name": "Zimax 500mg",
    "category": "Antibiotics",
    "description": "Effective treatment for bacterial infections.",
    "details": "This is a high-quality antibiotics manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳55.00 / strip",
    "manufacturer": "Incepta Pharmaceuticals Ltd.",
    "inStock": true,
    "packSize": "10 capsules per strip"
  },
  {
    "id": 75,
    "name": "Zimax 1000mg",
    "category": "Antibiotics",
    "description": "Effective treatment for bacterial infections.",
    "details": "This is a high-quality antibiotics manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳54.00 / strip",
    "manufacturer": "Eskayef Pharmaceuticals Ltd.",
    "inStock": true,
    "packSize": "10 capsules per strip"
  },
  {
    "id": 76,
    "name": "Ciprofloxacin 250mg",
    "category": "Antibiotics",
    "description": "Effective treatment for bacterial infections.",
    "details": "This is a high-quality antibiotics manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳82.00 / strip",
    "manufacturer": "Opsonin Pharma Limited",
    "inStock": true,
    "packSize": "10 capsules per strip"
  },
  {
    "id": 77,
    "name": "Ciprofloxacin 500mg",
    "category": "Antibiotics",
    "description": "Effective treatment for bacterial infections.",
    "details": "This is a high-quality antibiotics manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳90.00 / strip",
    "manufacturer": "Square Pharmaceuticals Ltd.",
    "inStock": true,
    "packSize": "10 capsules per strip"
  },
  {
    "id": 78,
    "name": "Ciprofloxacin 1000mg",
    "category": "Antibiotics",
    "description": "Effective treatment for bacterial infections.",
    "details": "This is a high-quality antibiotics manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳50.00 / strip",
    "manufacturer": "Square Pharmaceuticals Ltd.",
    "inStock": true,
    "packSize": "10 capsules per strip"
  },
  {
    "id": 79,
    "name": "Cifloxin 250mg",
    "category": "Antibiotics",
    "description": "Effective treatment for bacterial infections.",
    "details": "This is a high-quality antibiotics manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳86.00 / strip",
    "manufacturer": "Renata Limited",
    "inStock": true,
    "packSize": "10 capsules per strip"
  },
  {
    "id": 80,
    "name": "Cifloxin 500mg",
    "category": "Antibiotics",
    "description": "Effective treatment for bacterial infections.",
    "details": "This is a high-quality antibiotics manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳85.00 / strip",
    "manufacturer": "Renata Limited",
    "inStock": true,
    "packSize": "10 capsules per strip"
  },
  {
    "id": 81,
    "name": "Cifloxin 1000mg",
    "category": "Antibiotics",
    "description": "Effective treatment for bacterial infections.",
    "details": "This is a high-quality antibiotics manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳81.00 / strip",
    "manufacturer": "Aristopharma Ltd.",
    "inStock": true,
    "packSize": "10 capsules per strip"
  },
  {
    "id": 82,
    "name": "Levoflox 250mg",
    "category": "Antibiotics",
    "description": "Effective treatment for bacterial infections.",
    "details": "This is a high-quality antibiotics manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳66.00 / strip",
    "manufacturer": "ACME Laboratories Ltd.",
    "inStock": true,
    "packSize": "10 capsules per strip"
  },
  {
    "id": 83,
    "name": "Levoflox 500mg",
    "category": "Antibiotics",
    "description": "Effective treatment for bacterial infections.",
    "details": "This is a high-quality antibiotics manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳69.00 / strip",
    "manufacturer": "Eskayef Pharmaceuticals Ltd.",
    "inStock": true,
    "packSize": "10 capsules per strip"
  },
  {
    "id": 84,
    "name": "Levoflox 1000mg",
    "category": "Antibiotics",
    "description": "Effective treatment for bacterial infections.",
    "details": "This is a high-quality antibiotics manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳92.00 / strip",
    "manufacturer": "Square Pharmaceuticals Ltd.",
    "inStock": false,
    "packSize": "10 capsules per strip"
  },
  {
    "id": 85,
    "name": "Fluclox 250mg",
    "category": "Antibiotics",
    "description": "Effective treatment for bacterial infections.",
    "details": "This is a high-quality antibiotics manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳57.00 / strip",
    "manufacturer": "Renata Limited",
    "inStock": true,
    "packSize": "10 capsules per strip"
  },
  {
    "id": 86,
    "name": "Fluclox 500mg",
    "category": "Antibiotics",
    "description": "Effective treatment for bacterial infections.",
    "details": "This is a high-quality antibiotics manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳61.00 / strip",
    "manufacturer": "Renata Limited",
    "inStock": true,
    "packSize": "10 capsules per strip"
  },
  {
    "id": 87,
    "name": "Fluclox 1000mg",
    "category": "Antibiotics",
    "description": "Effective treatment for bacterial infections.",
    "details": "This is a high-quality antibiotics manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳90.00 / strip",
    "manufacturer": "Eskayef Pharmaceuticals Ltd.",
    "inStock": true,
    "packSize": "10 capsules per strip"
  },
  {
    "id": 88,
    "name": "Ceftriaxone 250mg",
    "category": "Antibiotics",
    "description": "Effective treatment for bacterial infections.",
    "details": "This is a high-quality antibiotics manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳68.00 / strip",
    "manufacturer": "Incepta Pharmaceuticals Ltd.",
    "inStock": true,
    "packSize": "10 capsules per strip"
  },
  {
    "id": 89,
    "name": "Ceftriaxone 500mg",
    "category": "Antibiotics",
    "description": "Effective treatment for bacterial infections.",
    "details": "This is a high-quality antibiotics manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳89.00 / strip",
    "manufacturer": "ACME Laboratories Ltd.",
    "inStock": false,
    "packSize": "10 capsules per strip"
  },
  {
    "id": 90,
    "name": "Ceftriaxone 1000mg",
    "category": "Antibiotics",
    "description": "Effective treatment for bacterial infections.",
    "details": "This is a high-quality antibiotics manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳81.00 / strip",
    "manufacturer": "Eskayef Pharmaceuticals Ltd.",
    "inStock": false,
    "packSize": "10 capsules per strip"
  },
  {
    "id": 91,
    "name": "Digital Thermometer (Mini)",
    "category": "Medical Devices",
    "description": "Reliable medical instruments and health monitors.",
    "details": "This is a high-quality medical devices manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳166.00 ",
    "manufacturer": "Square Pharmaceuticals Ltd.",
    "inStock": true,
    "packSize": "1 unit"
  },
  {
    "id": 92,
    "name": "Digital Thermometer (Basic)",
    "category": "Medical Devices",
    "description": "Reliable medical instruments and health monitors.",
    "details": "This is a high-quality medical devices manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳198.00 ",
    "manufacturer": "Aristopharma Ltd.",
    "inStock": true,
    "packSize": "1 unit"
  },
  {
    "id": 93,
    "name": "Digital Thermometer (Pro)",
    "category": "Medical Devices",
    "description": "Reliable medical instruments and health monitors.",
    "details": "This is a high-quality medical devices manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳191.00 ",
    "manufacturer": "Renata Limited",
    "inStock": false,
    "packSize": "1 unit"
  },
  {
    "id": 94,
    "name": "First Aid Kit (Mini)",
    "category": "Medical Devices",
    "description": "Reliable medical instruments and health monitors.",
    "details": "This is a high-quality medical devices manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳183.00 ",
    "manufacturer": "Incepta Pharmaceuticals Ltd.",
    "inStock": true,
    "packSize": "1 unit"
  },
  {
    "id": 95,
    "name": "First Aid Kit (Basic)",
    "category": "Medical Devices",
    "description": "Reliable medical instruments and health monitors.",
    "details": "This is a high-quality medical devices manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳178.00 ",
    "manufacturer": "ACME Laboratories Ltd.",
    "inStock": true,
    "packSize": "1 unit"
  },
  {
    "id": 96,
    "name": "First Aid Kit (Pro)",
    "category": "Medical Devices",
    "description": "Reliable medical instruments and health monitors.",
    "details": "This is a high-quality medical devices manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳168.00 ",
    "manufacturer": "Renata Limited",
    "inStock": true,
    "packSize": "1 unit"
  },
  {
    "id": 97,
    "name": "Blood Pressure Monitor (Mini)",
    "category": "Medical Devices",
    "description": "Reliable medical instruments and health monitors.",
    "details": "This is a high-quality medical devices manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳197.00 ",
    "manufacturer": "Aristopharma Ltd.",
    "inStock": true,
    "packSize": "1 unit"
  },
  {
    "id": 98,
    "name": "Blood Pressure Monitor (Basic)",
    "category": "Medical Devices",
    "description": "Reliable medical instruments and health monitors.",
    "details": "This is a high-quality medical devices manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳155.00 ",
    "manufacturer": "Renata Limited",
    "inStock": true,
    "packSize": "1 unit"
  },
  {
    "id": 99,
    "name": "Blood Pressure Monitor (Pro)",
    "category": "Medical Devices",
    "description": "Reliable medical instruments and health monitors.",
    "details": "This is a high-quality medical devices manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳193.00 ",
    "manufacturer": "Eskayef Pharmaceuticals Ltd.",
    "inStock": true,
    "packSize": "1 unit"
  },
  {
    "id": 100,
    "name": "Glucometer (Mini)",
    "category": "Medical Devices",
    "description": "Reliable medical instruments and health monitors.",
    "details": "This is a high-quality medical devices manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳166.00 ",
    "manufacturer": "Opsonin Pharma Limited",
    "inStock": true,
    "packSize": "1 unit"
  },
  {
    "id": 101,
    "name": "Glucometer (Basic)",
    "category": "Medical Devices",
    "description": "Reliable medical instruments and health monitors.",
    "details": "This is a high-quality medical devices manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳198.00 ",
    "manufacturer": "Square Pharmaceuticals Ltd.",
    "inStock": false,
    "packSize": "1 unit"
  },
  {
    "id": 102,
    "name": "Glucometer (Pro)",
    "category": "Medical Devices",
    "description": "Reliable medical instruments and health monitors.",
    "details": "This is a high-quality medical devices manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳152.00 ",
    "manufacturer": "Eskayef Pharmaceuticals Ltd.",
    "inStock": true,
    "packSize": "1 unit"
  },
  {
    "id": 103,
    "name": "Pulse Oximeter (Mini)",
    "category": "Medical Devices",
    "description": "Reliable medical instruments and health monitors.",
    "details": "This is a high-quality medical devices manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳193.00 ",
    "manufacturer": "Opsonin Pharma Limited",
    "inStock": true,
    "packSize": "1 unit"
  },
  {
    "id": 104,
    "name": "Pulse Oximeter (Basic)",
    "category": "Medical Devices",
    "description": "Reliable medical instruments and health monitors.",
    "details": "This is a high-quality medical devices manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳187.00 ",
    "manufacturer": "ACME Laboratories Ltd.",
    "inStock": true,
    "packSize": "1 unit"
  },
  {
    "id": 105,
    "name": "Pulse Oximeter (Pro)",
    "category": "Medical Devices",
    "description": "Reliable medical instruments and health monitors.",
    "details": "This is a high-quality medical devices manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳182.00 ",
    "manufacturer": "Square Pharmaceuticals Ltd.",
    "inStock": true,
    "packSize": "1 unit"
  },
  {
    "id": 106,
    "name": "Nebulizer (Mini)",
    "category": "Medical Devices",
    "description": "Reliable medical instruments and health monitors.",
    "details": "This is a high-quality medical devices manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳165.00 ",
    "manufacturer": "Aristopharma Ltd.",
    "inStock": true,
    "packSize": "1 unit"
  },
  {
    "id": 107,
    "name": "Nebulizer (Basic)",
    "category": "Medical Devices",
    "description": "Reliable medical instruments and health monitors.",
    "details": "This is a high-quality medical devices manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳157.00 ",
    "manufacturer": "Opsonin Pharma Limited",
    "inStock": true,
    "packSize": "1 unit"
  },
  {
    "id": 108,
    "name": "Nebulizer (Pro)",
    "category": "Medical Devices",
    "description": "Reliable medical instruments and health monitors.",
    "details": "This is a high-quality medical devices manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳182.00 ",
    "manufacturer": "Opsonin Pharma Limited",
    "inStock": true,
    "packSize": "1 unit"
  },
  {
    "id": 109,
    "name": "Hot Water Bag (Mini)",
    "category": "Medical Devices",
    "description": "Reliable medical instruments and health monitors.",
    "details": "This is a high-quality medical devices manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳192.00 ",
    "manufacturer": "Incepta Pharmaceuticals Ltd.",
    "inStock": true,
    "packSize": "1 unit"
  },
  {
    "id": 110,
    "name": "Hot Water Bag (Basic)",
    "category": "Medical Devices",
    "description": "Reliable medical instruments and health monitors.",
    "details": "This is a high-quality medical devices manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳189.00 ",
    "manufacturer": "Renata Limited",
    "inStock": true,
    "packSize": "1 unit"
  },
  {
    "id": 111,
    "name": "Hot Water Bag (Pro)",
    "category": "Medical Devices",
    "description": "Reliable medical instruments and health monitors.",
    "details": "This is a high-quality medical devices manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳194.00 ",
    "manufacturer": "Beximco Pharmaceuticals Ltd.",
    "inStock": true,
    "packSize": "1 unit"
  },
  {
    "id": 112,
    "name": "Weighing Scale (Mini)",
    "category": "Medical Devices",
    "description": "Reliable medical instruments and health monitors.",
    "details": "This is a high-quality medical devices manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳192.00 ",
    "manufacturer": "Incepta Pharmaceuticals Ltd.",
    "inStock": true,
    "packSize": "1 unit"
  },
  {
    "id": 113,
    "name": "Weighing Scale (Basic)",
    "category": "Medical Devices",
    "description": "Reliable medical instruments and health monitors.",
    "details": "This is a high-quality medical devices manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳173.00 ",
    "manufacturer": "Square Pharmaceuticals Ltd.",
    "inStock": true,
    "packSize": "1 unit"
  },
  {
    "id": 114,
    "name": "Weighing Scale (Pro)",
    "category": "Medical Devices",
    "description": "Reliable medical instruments and health monitors.",
    "details": "This is a high-quality medical devices manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳169.00 ",
    "manufacturer": "Aristopharma Ltd.",
    "inStock": true,
    "packSize": "1 unit"
  },
  {
    "id": 115,
    "name": "Surgical Mask (Mini)",
    "category": "Medical Devices",
    "description": "Reliable medical instruments and health monitors.",
    "details": "This is a high-quality medical devices manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳186.00 ",
    "manufacturer": "Square Pharmaceuticals Ltd.",
    "inStock": true,
    "packSize": "1 unit"
  },
  {
    "id": 116,
    "name": "Surgical Mask (Basic)",
    "category": "Medical Devices",
    "description": "Reliable medical instruments and health monitors.",
    "details": "This is a high-quality medical devices manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳162.00 ",
    "manufacturer": "Incepta Pharmaceuticals Ltd.",
    "inStock": true,
    "packSize": "1 unit"
  },
  {
    "id": 117,
    "name": "Surgical Mask (Pro)",
    "category": "Medical Devices",
    "description": "Reliable medical instruments and health monitors.",
    "details": "This is a high-quality medical devices manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳172.00 ",
    "manufacturer": "ACME Laboratories Ltd.",
    "inStock": true,
    "packSize": "1 unit"
  },
  {
    "id": 118,
    "name": "Sterile Gloves (Mini)",
    "category": "Medical Devices",
    "description": "Reliable medical instruments and health monitors.",
    "details": "This is a high-quality medical devices manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳159.00 ",
    "manufacturer": "ACME Laboratories Ltd.",
    "inStock": true,
    "packSize": "1 unit"
  },
  {
    "id": 119,
    "name": "Sterile Gloves (Basic)",
    "category": "Medical Devices",
    "description": "Reliable medical instruments and health monitors.",
    "details": "This is a high-quality medical devices manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳163.00 ",
    "manufacturer": "Renata Limited",
    "inStock": true,
    "packSize": "1 unit"
  },
  {
    "id": 120,
    "name": "Sterile Gloves (Pro)",
    "category": "Medical Devices",
    "description": "Reliable medical instruments and health monitors.",
    "details": "This is a high-quality medical devices manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳167.00 ",
    "manufacturer": "Eskayef Pharmaceuticals Ltd.",
    "inStock": true,
    "packSize": "1 unit"
  },
  {
    "id": 121,
    "name": "Vitamin C 250mg",
    "category": "Supplements",
    "description": "Daily dietary supplements for better health.",
    "details": "This is a high-quality supplements manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳117.00 / strip",
    "manufacturer": "Opsonin Pharma Limited",
    "inStock": true,
    "packSize": "30 tablets"
  },
  {
    "id": 122,
    "name": "Vitamin C 500mg",
    "category": "Supplements",
    "description": "Daily dietary supplements for better health.",
    "details": "This is a high-quality supplements manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳93.00 / strip",
    "manufacturer": "Incepta Pharmaceuticals Ltd.",
    "inStock": true,
    "packSize": "30 tablets"
  },
  {
    "id": 123,
    "name": "Vitamin C 1000mg",
    "category": "Supplements",
    "description": "Daily dietary supplements for better health.",
    "details": "This is a high-quality supplements manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳97.00 / strip",
    "manufacturer": "Eskayef Pharmaceuticals Ltd.",
    "inStock": false,
    "packSize": "30 tablets"
  },
  {
    "id": 124,
    "name": "Vitamin D3 250mg",
    "category": "Supplements",
    "description": "Daily dietary supplements for better health.",
    "details": "This is a high-quality supplements manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳114.00 / strip",
    "manufacturer": "Eskayef Pharmaceuticals Ltd.",
    "inStock": true,
    "packSize": "30 tablets"
  },
  {
    "id": 125,
    "name": "Vitamin D3 500mg",
    "category": "Supplements",
    "description": "Daily dietary supplements for better health.",
    "details": "This is a high-quality supplements manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳124.00 / strip",
    "manufacturer": "ACME Laboratories Ltd.",
    "inStock": true,
    "packSize": "30 tablets"
  },
  {
    "id": 126,
    "name": "Vitamin D3 1000mg",
    "category": "Supplements",
    "description": "Daily dietary supplements for better health.",
    "details": "This is a high-quality supplements manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳106.00 / strip",
    "manufacturer": "Eskayef Pharmaceuticals Ltd.",
    "inStock": true,
    "packSize": "30 tablets"
  },
  {
    "id": 127,
    "name": "Multivitamin 250mg",
    "category": "Supplements",
    "description": "Daily dietary supplements for better health.",
    "details": "This is a high-quality supplements manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳88.00 / strip",
    "manufacturer": "Aristopharma Ltd.",
    "inStock": true,
    "packSize": "30 tablets"
  },
  {
    "id": 128,
    "name": "Multivitamin 500mg",
    "category": "Supplements",
    "description": "Daily dietary supplements for better health.",
    "details": "This is a high-quality supplements manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳98.00 / strip",
    "manufacturer": "Renata Limited",
    "inStock": true,
    "packSize": "30 tablets"
  },
  {
    "id": 129,
    "name": "Multivitamin 1000mg",
    "category": "Supplements",
    "description": "Daily dietary supplements for better health.",
    "details": "This is a high-quality supplements manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳99.00 / strip",
    "manufacturer": "Incepta Pharmaceuticals Ltd.",
    "inStock": false,
    "packSize": "30 tablets"
  },
  {
    "id": 130,
    "name": "Calcium + D3 250mg",
    "category": "Supplements",
    "description": "Daily dietary supplements for better health.",
    "details": "This is a high-quality supplements manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳126.00 / strip",
    "manufacturer": "Renata Limited",
    "inStock": true,
    "packSize": "30 tablets"
  },
  {
    "id": 131,
    "name": "Calcium + D3 500mg",
    "category": "Supplements",
    "description": "Daily dietary supplements for better health.",
    "details": "This is a high-quality supplements manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳99.00 / strip",
    "manufacturer": "Beximco Pharmaceuticals Ltd.",
    "inStock": false,
    "packSize": "30 tablets"
  },
  {
    "id": 132,
    "name": "Calcium + D3 1000mg",
    "category": "Supplements",
    "description": "Daily dietary supplements for better health.",
    "details": "This is a high-quality supplements manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳90.00 / strip",
    "manufacturer": "Eskayef Pharmaceuticals Ltd.",
    "inStock": true,
    "packSize": "30 tablets"
  },
  {
    "id": 133,
    "name": "Iron Supplement 250mg",
    "category": "Supplements",
    "description": "Daily dietary supplements for better health.",
    "details": "This is a high-quality supplements manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳108.00 / strip",
    "manufacturer": "Beximco Pharmaceuticals Ltd.",
    "inStock": true,
    "packSize": "30 tablets"
  },
  {
    "id": 134,
    "name": "Iron Supplement 500mg",
    "category": "Supplements",
    "description": "Daily dietary supplements for better health.",
    "details": "This is a high-quality supplements manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳126.00 / strip",
    "manufacturer": "Beximco Pharmaceuticals Ltd.",
    "inStock": true,
    "packSize": "30 tablets"
  },
  {
    "id": 135,
    "name": "Iron Supplement 1000mg",
    "category": "Supplements",
    "description": "Daily dietary supplements for better health.",
    "details": "This is a high-quality supplements manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳96.00 / strip",
    "manufacturer": "ACME Laboratories Ltd.",
    "inStock": false,
    "packSize": "30 tablets"
  },
  {
    "id": 136,
    "name": "Omega 3 250mg",
    "category": "Supplements",
    "description": "Daily dietary supplements for better health.",
    "details": "This is a high-quality supplements manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳127.00 / strip",
    "manufacturer": "Renata Limited",
    "inStock": false,
    "packSize": "30 tablets"
  },
  {
    "id": 137,
    "name": "Omega 3 500mg",
    "category": "Supplements",
    "description": "Daily dietary supplements for better health.",
    "details": "This is a high-quality supplements manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳118.00 / strip",
    "manufacturer": "Incepta Pharmaceuticals Ltd.",
    "inStock": true,
    "packSize": "30 tablets"
  },
  {
    "id": 138,
    "name": "Omega 3 1000mg",
    "category": "Supplements",
    "description": "Daily dietary supplements for better health.",
    "details": "This is a high-quality supplements manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳111.00 / strip",
    "manufacturer": "Beximco Pharmaceuticals Ltd.",
    "inStock": true,
    "packSize": "30 tablets"
  },
  {
    "id": 139,
    "name": "Zinc Tablet 250mg",
    "category": "Supplements",
    "description": "Daily dietary supplements for better health.",
    "details": "This is a high-quality supplements manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳89.00 / strip",
    "manufacturer": "Aristopharma Ltd.",
    "inStock": true,
    "packSize": "30 tablets"
  },
  {
    "id": 140,
    "name": "Zinc Tablet 500mg",
    "category": "Supplements",
    "description": "Daily dietary supplements for better health.",
    "details": "This is a high-quality supplements manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳96.00 / strip",
    "manufacturer": "Incepta Pharmaceuticals Ltd.",
    "inStock": true,
    "packSize": "30 tablets"
  },
  {
    "id": 141,
    "name": "Zinc Tablet 1000mg",
    "category": "Supplements",
    "description": "Daily dietary supplements for better health.",
    "details": "This is a high-quality supplements manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳82.00 / strip",
    "manufacturer": "Eskayef Pharmaceuticals Ltd.",
    "inStock": true,
    "packSize": "30 tablets"
  },
  {
    "id": 142,
    "name": "B-Complex 250mg",
    "category": "Supplements",
    "description": "Daily dietary supplements for better health.",
    "details": "This is a high-quality supplements manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳96.00 / strip",
    "manufacturer": "Renata Limited",
    "inStock": true,
    "packSize": "30 tablets"
  },
  {
    "id": 143,
    "name": "B-Complex 500mg",
    "category": "Supplements",
    "description": "Daily dietary supplements for better health.",
    "details": "This is a high-quality supplements manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳111.00 / strip",
    "manufacturer": "Renata Limited",
    "inStock": true,
    "packSize": "30 tablets"
  },
  {
    "id": 144,
    "name": "B-Complex 1000mg",
    "category": "Supplements",
    "description": "Daily dietary supplements for better health.",
    "details": "This is a high-quality supplements manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳102.00 / strip",
    "manufacturer": "ACME Laboratories Ltd.",
    "inStock": true,
    "packSize": "30 tablets"
  },
  {
    "id": 145,
    "name": "Protein Powder 250mg",
    "category": "Supplements",
    "description": "Daily dietary supplements for better health.",
    "details": "This is a high-quality supplements manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳89.00 / strip",
    "manufacturer": "Opsonin Pharma Limited",
    "inStock": true,
    "packSize": "30 tablets"
  },
  {
    "id": 146,
    "name": "Protein Powder 500mg",
    "category": "Supplements",
    "description": "Daily dietary supplements for better health.",
    "details": "This is a high-quality supplements manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳90.00 / strip",
    "manufacturer": "Square Pharmaceuticals Ltd.",
    "inStock": true,
    "packSize": "30 tablets"
  },
  {
    "id": 147,
    "name": "Protein Powder 1000mg",
    "category": "Supplements",
    "description": "Daily dietary supplements for better health.",
    "details": "This is a high-quality supplements manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳90.00 / strip",
    "manufacturer": "ACME Laboratories Ltd.",
    "inStock": false,
    "packSize": "30 tablets"
  },
  {
    "id": 148,
    "name": "Folic Acid 250mg",
    "category": "Supplements",
    "description": "Daily dietary supplements for better health.",
    "details": "This is a high-quality supplements manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳117.00 / strip",
    "manufacturer": "ACME Laboratories Ltd.",
    "inStock": true,
    "packSize": "30 tablets"
  },
  {
    "id": 149,
    "name": "Folic Acid 500mg",
    "category": "Supplements",
    "description": "Daily dietary supplements for better health.",
    "details": "This is a high-quality supplements manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳83.00 / strip",
    "manufacturer": "Incepta Pharmaceuticals Ltd.",
    "inStock": true,
    "packSize": "30 tablets"
  },
  {
    "id": 150,
    "name": "Folic Acid 1000mg",
    "category": "Supplements",
    "description": "Daily dietary supplements for better health.",
    "details": "This is a high-quality supplements manufactured according to the best pharmaceutical standards. Always read the label and follow the directions for use. If symptoms persist, talk to your health professional.",
    "price": "৳81.00 / strip",
    "manufacturer": "Beximco Pharmaceuticals Ltd.",
    "inStock": true,
    "packSize": "30 tablets"
  }
];
